# Introducción a NumPy

NumPy es una extensión de Python, que le agrega mayor soporte para vectores y matrices, constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con esos vectores o matrices.

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([1, 2, 3])

Numpy convierte todos los elementos de un array al mismo tipo de elemento.

In [14]:
b = np.array([1.12312,2,3]) # todos a flotantes

b

In [13]:
c = np.array([1.12312,2,"dadasd"]) # todos a cadenas

In [11]:
c

array(['1.12312', '2', 'dadasd'], dtype='<U32')

Podemos incluso forzar el tipo de un array con `dtype`.

In [15]:
d = np.array([1,2,3], dtype='float32')

Es fácil crear y ver matrices:

In [16]:
e = np.array([[0,0,0], [1,1,1], [2,2,2]])

In [17]:
e

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

Se pueden crear arrays de ceros y unos en un momento. Esto nos puede servir para hacer una máscara (como por ejemplo en los filtros de instagram).

In [26]:
np.zeros(5) # una dimensión

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,4)) # 3 x 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Con `full` llenamos la matriz con el número indicado

In [28]:
np.full((4,4), 15)

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [29]:
np.full((4,3,2), 15, dtype="float") #profundidad(z), filas y columnas

array([[[15., 15.],
        [15., 15.],
        [15., 15.]],

       [[15., 15.],
        [15., 15.],
        [15., 15.]],

       [[15., 15.],
        [15., 15.],
        [15., 15.]],

       [[15., 15.],
        [15., 15.],
        [15., 15.]]])

In [34]:
np.arange(0,10) # array usando range(inicio,fin,step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [38]:
np.linspace(0, 10, 10) # (mínimo, máximo, cuántos valores quieres dentro) #equidistantes

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [40]:
np.random.random((3,3)) # datos aleatorios, entre 0 y 1, distribuidos uniformemente

array([[0.15643609, 0.11269101, 0.83583047],
       [0.3814178 , 0.79765132, 0.10837773],
       [0.69381183, 0.36204625, 0.04783755]])

In [52]:
np.random.normal(0, 1 ,(3 ,3)) # podemos indicar la media y 
#la desviación estándar de la distribución normal

array([[-1.93821768, -0.17197212,  0.85056153],
       [ 0.25000099,  0.51164398, -1.3740405 ],
       [-1.61265242,  0.19697467, -0.84006013]])

In [45]:
np.random.randint(0,30, (4,4)) # igual, pero con enteros

array([[ 0, 26,  2, 25],
       [23, 18, 25, 23],
       [16, 24, 11, 23],
       [25,  5, 19, 28]])

In [46]:
np.eye(4) # matriz con diagonal a 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.empty((3, 5)) # rellena con cosas de la memoria

array([[1.79408596e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])